development:
        store: shopscreenbids.myshopify.com
        password: snowman21
        theme_id: "live"
        bucket_size: 40
        refill_rate: 2
        ignore_files:
                - "*.swp"
                - "*~"
                - "config/settings_data.json"
 
